[project]
name = "chatmiddleware"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask-cors>=5.0.0",
    "flask>=3.1.0",
    "load-dotenv>=0.1.0",
    "google-generativeai>=0.8.3",
    "pytest>=8.3.4",
]
